import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Provider from "@/components/auth/Provider";
import { getServerSession } from "next-auth/next";
import { authConfig } from "@/pages/api/auth/[...nextauth]";
import { Session } from "inspector";

const inter = Inter({ subsets: ["latin"] });

const linktw = "p-2 bg-black text-white";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authConfig);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-2">
          <Link className={linktw} href={"/dashboard"}>
            Dashboard
          </Link>
          <Link className={linktw} href={"/"}>
            Home
          </Link>
          <Link className={linktw} href={"/user"}>
            User
          </Link>
          <Link className={linktw} href={"/login"}>
            Login
          </Link>
          <Link className={linktw} href={"/register"}>
            Register
          </Link>
        </div>
        <Provider session={session}>{children}</Provider>
      </body>
    </html>
  );
}
