import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

const linktw = "p-2 bg-black text-white";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-2">
          <Link className={linktw} href={"/dashboard"}>
            Dashboard
          </Link>
          <Link className={linktw} href={"/"}>
            Home
          </Link>
          <Link className={linktw} href={"/user"}>
            User
          </Link>
          <Link className={linktw} href={"/login"}>
            Login
          </Link>
          <Link className={linktw} href={"/register"}>
            Register
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
